services:
  - type: web
    name: odyssey-portal
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://tmf-bss-showcase-01.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
