"""initial TMF entity schema

Revision ID: 83f9f9793ba4
Revises: 
Create Date: 2026-07-23 23:58:16.315310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83f9f9793ba4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_table('individuals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individuals_email'), 'individuals', ['email'], unique=False)
    op.create_index(op.f('ix_individuals_full_name'), 'individuals', ['full_name'], unique=False)
    op.create_index(op.f('ix_individuals_status'), 'individuals', ['status'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_index(op.f('ix_organisations_status'), 'organisations', ['status'], unique=False)
    op.create_table('product_offerings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lifecycle_status', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_offerings_lifecycle_status'), 'product_offerings', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_product_offerings_name'), 'product_offerings', ['name'], unique=False)
    op.create_table('product_specifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_specifications_name'), 'product_specifications', ['name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('party_id', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['individuals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_party_id'), 'customers', ['party_id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('billing_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_accounts_customer_id'), 'billing_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_billing_accounts_name'), 'billing_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_billing_accounts_state'), 'billing_accounts', ['state'], unique=False)
    op.create_table('product_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('offering_id', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_orders_customer_id'), 'product_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_orders_offering_id'), 'product_orders', ['offering_id'], unique=False)
    op.create_index(op.f('ix_product_orders_state'), 'product_orders', ['state'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=True),
    sa.Column('offering_id', sa.String(length=64), nullable=True),
    sa.Column('doc', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['product_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_customer_id'), 'products', ['customer_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_offering_id'), 'products', ['offering_id'], unique=False)
    op.create_index('ix_products_order_customer', 'products', ['order_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_products_order_id'), 'products', ['order_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_order_id'), table_name='products')
    op.drop_index('ix_products_order_customer', table_name='products')
    op.drop_index(op.f('ix_products_offering_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_customer_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_orders_state'), table_name='product_orders')
    op.drop_index(op.f('ix_product_orders_offering_id'), table_name='product_orders')
    op.drop_index(op.f('ix_product_orders_customer_id'), table_name='product_orders')
    op.drop_table('product_orders')
    op.drop_index(op.f('ix_billing_accounts_state'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_name'), table_name='billing_accounts')
    op.drop_index(op.f('ix_billing_accounts_customer_id'), table_name='billing_accounts')
    op.drop_table('billing_accounts')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_party_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_product_specifications_name'), table_name='product_specifications')
    op.drop_table('product_specifications')
    op.drop_index(op.f('ix_product_offerings_name'), table_name='product_offerings')
    op.drop_index(op.f('ix_product_offerings_lifecycle_status'), table_name='product_offerings')
    op.drop_table('product_offerings')
    op.drop_index(op.f('ix_organisations_status'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_individuals_status'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_full_name'), table_name='individuals')
    op.drop_index(op.f('ix_individuals_email'), table_name='individuals')
    op.drop_table('individuals')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
